name: Run RestSharp Tests

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v3
   - name: Setup .NET
     uses: actions/setup-dotnet@v2
     with:
       dotnet-version: '8.0'

   - name: Restore dependencies
     run: dotnet restore

   - name: build
     run: dotnent build

   - name: run tests
     run: dotnet test --no-restore --verbosity normal
